app/Transformers/DivisionBasicTransformer.php

Consider moving to slugs in place of abbreviations for implicit route binding at some point

add division slug

---

app/AOD/MemberSync/SyncMemberData.php

so we can block the handleses's

add privacy flag tracking

---

app/Http/Controllers/TicketController.php

Self-assign reopened tickets

---

app/Models/Division.php
resources/views/division/partials/notices.blade.php
resources/views/division/reports/voice-report.blade.php

Fix discord / ts issues alert

---

resources/views/training/partials/sgt/ts-moderation.md

Convert to table

---

resources/views/training/partials/sgt/ds-moderation.md
resources/views/training/partials/sgt/misc-info.md
resources/views/training/partials/sgt/ts-moderation.md

- Moved Steaks in Microwave Easter Egg to MISC page
- added DS mod point RE moving people in Voice Channels
- added TS mod point RE Connection Information

Dev manimal prime

---

resources/views/platoon/edit.blade.php
resources/views/platoon/partials/edit-platoon-button.blade.php

This should fix two issues editing platoons including the Manage Platoon and Save buttons.

Update platoon routes to use slugs

---

resources/views/division/partials/filter-inactive.blade.php

Updates the filter dropdown and the reset button on the Inactives view to use slugs.

Update filtering on Inactives view to use slugs

---

app/Http/Controllers/Admin/MemberRequestController.php
app/Http/Controllers/Controller.php
app/Http/Controllers/DeveloperController.php
app/Http/Controllers/DivisionController.php
app/Http/Controllers/DivisionStructureController.php
app/Http/Controllers/ImpersonationController.php
app/Http/Controllers/InactiveMemberController.php
app/Http/Controllers/LeaveController.php
app/Http/Controllers/MemberController.php
app/Http/Controllers/NoteController.php
app/Http/Controllers/PlatoonController.php
app/Http/Controllers/RecruitingController.php
app/Http/Controllers/SquadController.php
app/Http/Controllers/TicketCommentController.php
app/Http/Controllers/TicketController.php
app/Http/Controllers/TrainingController.php
app/Http/Controllers/UserSettingsController.php

Also support defining a title, and important toasts (non-disappearing)

Refactor success toasts

---

app/Notifications/MemberRemoved.php

A lot of commits for not a lot of work. Don't worry, I'll squash...

Member removal tweaks

---

app/Http/Controllers/InactiveMemberController.php
app/Notifications/MemberRemoved.php
resources/views/division/forms/general-settings.blade.php
resources/views/division/partials/inactive-members.blade.php

Give divisions a way to determine what metric is used for inactivity removals

Add temporary opt-in for discord activity

---

app/Http/Controllers/InactiveMemberController.php
app/Presenters/MemberPresenter.php
resources/views/division/partials/inactive-members.blade.php
resources/views/division/reports/voice-report.blade.php
resources/views/member/partials/member-data-row.blade.php

Addresses a couple of issues with the original change

Fix discord inactives

---

app/Http/Controllers/InactiveMemberController.php

May restore it later for discord opt in divisions

Drop filter from inactives

---

app/Http/Controllers/DivisionStructureController.php

Don't alert if nothing changed

---

database/migrations/2024_05_26_110404_add_indexes_to_members.php

Also add index to member_requests.member_id

Add unique index to members.clan_id

---

resources/views/division/inactive-members.blade.php

Adds a flag icon to inactive page tabs to match the TS and Discord icons.

Add flag icon to inactive page tabs

---

app/Filament/Resources/DivisionResource.php
app/Models/Division.php
database/migrations/2024_07_22_155600_add_logo_column_to_divisions_table.php
public/storage
resources/views/leave/edit.blade.php
resources/views/leave/forms/create-leave.blade.php
resources/views/leave/forms/delete-leave.blade.php
resources/views/leave/forms/edit-leave.blade.php

- Allows for upload of the division logo at the point of creation (or later)
- Cleans up overall fields
- Removes the need to keep division logos in version control for either the tracker or the site - these can be cleaned up later once we've migrated them over
- LOA bug fixes

Release develop

---

app/AOD/ClanForumPermissions.php
app/Http/Requests/CreateDivision.php
app/Http/Requests/CreatePlatoonForm.php
app/Http/Requests/CreateSquadForm.php
app/Http/Requests/UpdatePlatoonForm.php
app/Http/Requests/UpdateSquadForm.php

Update assignPosition functions to use Position enum

---

app/Http/Controllers/MemberController.php

Remove eager load from the recruits list.

MemberController Rank Fixes

---

app/Http/Controllers/Admin/MemberRequestController.php
app/Http/Controllers/AdminController.php
app/Http/Controllers/Division/ReportController.php
app/Http/Controllers/DivisionNoteController.php
app/Http/Controllers/InactiveMemberController.php
app/Http/Controllers/MemberController.php
app/Http/Controllers/SquadController.php
app/Repositories/MemberRepository.php
resources/views/division/part-time.blade.php
resources/views/division/partials/flagged-members.blade.php
resources/views/division/partials/general-sergeants.blade.php
resources/views/division/partials/inactive-members.blade.php
resources/views/leave/partials/leave-table.blade.php
resources/views/platoon/forms/assign-members-form.blade.php
resources/views/squad/forms/assign-members-form.blade.php

References and eager loads missed during the previous update

Rank hotfixes

---

app/Enums/DiscordStatus.php
app/Enums/Position.php
app/Filament/Resources/MemberResource.php
app/Http/Controllers/Division/ReportController.php
app/Http/Controllers/InactiveMemberController.php
app/Models/Division.php
app/Models/Member.php
composer.lock
resources/views/division/partials/inactive-members.blade.php
resources/views/division/partials/notices.blade.php
resources/views/division/partials/voice-status.blade.php
resources/views/division/reports/voice-report.blade.php

- Provide discord status on inactives page
- Refactor misconfigured discord state to scope on member model
- Include null `last_voice_activity` on inactive list

Inactive improvements

---

app/Models/User.php
app/Policies/ApiTokenPolicy.php
app/Policies/MemberPolicy.php
app/Policies/UserPolicy.php
resources/views/member/partials/general-information.blade.php

Several more rank fixes due to enum comparison issues. It also allows CO and XO dates for non-Sgt+ (Cpl) COs and XOs.

More rank fixes due to enum comparison issues

---

app/AOD/RssFeedService.php
app/Channels/Messages/BotChannelMessage.php
app/Console/Commands/FetchApplicationFeeds.php
app/Filament/Mod/Resources/DivisionResource.php
app/Notifications/NewDivisionApplication.php

- Monitor RSS feeds provided by divisions for new applications
- Cache found threads so we don't send duplicate reports

Implement application tracking

---

app/Filament/Mod/Resources/RankActionResource.php
app/Models/Member.php
app/Models/RankAction.php
app/Notifications/Channel/NotifyAdminSgtRequestComplete.php
resources/views/filament/forms/components/status-badge.blade.php
resources/views/filament/forms/components/type-badge.blade.php

Reorganizes some of the logic for the rank action resource to scopes on the model and member.  Also restores a badge count for later use in a notice

Rank action improvements

---

app/Filament/Mod/Resources/RankActionResource.php
app/Models/Member.php
app/Models/RankAction.php
app/Notifications/Channel/NotifyAdminSgtRequestComplete.php
app/Notifications/DM/NotifyMemberAwardReceived.php
resources/views/filament/forms/components/status-badge.blade.php
resources/views/filament/forms/components/type-badge.blade.php

- Fix a route typo in award notifications
- SGT request complete notifications are now green
- Query scope organization to clean up the `RankActionResource`
- Navigation badge for rank actions

Release fixes

---

database/seeders/ClanSeeder.php

Fixed a duplicated block of code preventing the ClanSeeder from running + formatting.

Seeder fix

---

app/Console/Commands/MemberSync.php
app/Filament/Mod/Resources/MemberResource/RelationManagers/RankActionsRelationManager.php
app/Filament/Mod/Resources/RankActionResource.php
app/Filament/Mod/Resources/RankActionResource/Pages/EditRankAction.php
app/Http/Controllers/PromotionController.php
app/Models/RankAction.php

- Stop member data syncs when an error is detected
- Hide extra-division rank actions unless the user is an admin
- Dev seeder fixes
- Filter unapproved rank actions in member resource

Release dev changes - 4/12

---

app/Console/Commands/MemberSync.php
app/Notifications/Channel/NotifyDivisionMemberRemoved.php

Adds a notification to the forum sync process that triggers when a member is removed from the forums and that separation is picked up by the sync.

Notify on sync removal

---

app/Filament/Admin/Resources/AwardResource/Pages/EditAward.php
app/Models/Award.php

Ensures we don't brick member profiles when an award is deleted

Cascade delete member awards

---

app/Http/Controllers/DivisionController.php
app/Http/Controllers/PlatoonController.php
app/Repositories/DivisionRepository.php
app/Repositories/PlatoonRepository.php
app/Repositories/SquadRepository.php
app/Traits/HasActivityGraph.php

- Activity graphs now reflect division-specific inactivity settings
- Moves calculations to a trait and DRYs up division, platoon, and squad repositories
- Cleans up deprecated forum activity code

Improved activity graphs

---

app/Http/Controllers/DivisionController.php
app/Http/Controllers/PlatoonController.php
app/Repositories/DivisionRepository.php
app/Repositories/PlatoonRepository.php
app/Repositories/SquadRepository.php
app/Traits/HasActivityGraph.php

- Activity graphs now reflect division-specific inactivity settings
- Moves calculations to a trait and DRYs up division, platoon, and squad repositories
- Cleans up deprecated forum activity code

Improved activity graphs (#524)

---

app/Models/User.php
resources/views/member/partials/part-time-divisions.blade.php

Aapparently includes some style changes too

Release hotfixes

---

app/Http/Controllers/ReportsController.php

CO/XO should sort first followed by platoon, squad leads, followed by clan admin
Closes #547

Sort by rank, then by position
