app/Channels/Messages/DiscordMessage.php
app/Channels/Messages/DiscordMessageReact.php
app/Http/Controllers/TicketController.php
app/Notifications/NotifyAdminTicketCreated.php
app/Notifications/TicketReaction.php
database/factories/TicketFactory.php
database/migrations/2023_05_17_143601_add_message_id_to_tickets_table.php

Leverages the discord bot command `!react` to apply reacts based on resolution, rejection, and assignment of tickets. Mostly a helper process for admins to see that tickets have been handled (or not) without clicking into them

Implement ticket reactions

---

app/AOD/MemberSync/SyncMemberData.php
app/Http/Controllers/Division/ReportController.php
app/Models/Division.php
app/Models/Member.php
app/Models/Member/HasCustomAttributes.php
database/migrations/2024_03_21_080438_add_discord_data_to_member_sync.php
database/migrations/2024_03_21_083940_add_discord_member_data.php
resources/views/application/header.blade.php
resources/views/division/partials/tools-links.blade.php
resources/views/division/partials/voice-status.blade.php
resources/views/division/reports/voice-report.blade.php
resources/views/member/partials/general-information.blade.php
resources/views/member/partials/voice-status.blade.php
routes/Breadcrumbs/division.php
routes/partials/divisions.php

This PR adds a few things in support of Discord integration, specifically the need to track activity for members.
- Adds new discord data to member / division forum sync
- Adds a division level report for divisions to identify members with issues
- Adds a discord status to member pages

Implement Discord data, reports

---

app/Repositories/DivisionRepository.php
resources/views/division/partials/anniversaries.blade.php

Update the Anniversaries section on the Division view to indicate the **upcoming** anniversary for the member in that month rather than their current tenure. Extra logic was needed, so the extra day is only added if the date is earlier in the month than their anniversary.

Add an extra year to anniversaries on Division view.

---

resources/views/division/partials/anniversaries.blade.php

Trophies are showing for members with less than 5 years of membership due to edb010c2cacc322bda8725c112e2c2b7a41c92af. This commit corrects that display.
Current
Corrected

Fix trophies again so the 5+ trophy is only displayed for 5+ members

---

app/Channels/Messages/BotMessage.php
app/Models/Ticket.php
app/Notifications/DivisionEdited.php
app/Notifications/MemberNameChanged.php
app/Notifications/MemberRemoved.php
app/Notifications/MemberRequestApproved.php
app/Notifications/MemberRequestDenied.php
app/Notifications/MemberRequestHoldLifted.php
app/Notifications/MemberRequestPutOnHold.php
app/Notifications/MemberTransferred.php
app/Notifications/NewExternalRecruit.php
app/Notifications/NewMemberRecruited.php
app/Notifications/NotifyAdminTicketCreated.php
app/Notifications/PartTimeMemberRemoved.php
config/app.php

This PR converts all of the channel-based messages to BotChannel. DMs and reactions haven't been updated yet.
Please make sure the environment variable, BOT_API_BASE_URL, is defined before deploying since the hard-coded value was removed.

Port channel-based bot messages over to BotChannel

---

app/AOD/MemberSync/SyncMemberData.php

Originally we only notified the incoming division of a new transfer. This adds a notification to outgoing as well.

Notify all transfers

---

app/Channels/Messages/BotReactMessage.php
app/Http/Controllers/TicketController.php
app/Http/Requests/CreateTicket.php
app/Notifications/TicketReaction.php

This moves ticket persistence to a request object. It also removes the default message id since we no longer need to inform the bot of a generic UUID, we get one when the message is posted as well as a minor refactor to refer to the message id from the notifiable rather than setting it separately in the notification

Reactions tweak

---

resources/views/division/reports/voice-report.blade.php

An error is thrown when a member without an assigned platoon is displayed on the voice report due to a property read attempt on a null Platoon object. 
This will happen for the CO, XO, General Sgt, Clan Admin positions, and an unassigned member after a division transfer or assignment reset.

Use nullsafe operator when displaying platoons on voice report

---

app/Models/Helpers.php
app/Models/Member/HasCustomAttributes.php
app/Presenters/MemberPresenter.php
resources/views/member/partials/general-information.blade.php
resources/views/member/partials/member-data-row.blade.php

Updates member activity display on profile and division member lists to represent their status better.
Notable changes:
- Fixes the epoch bug - these and other invalid dates will display as "Never"
- Display a "Pending" status while a member request is pending approval
- Consolidates most of the logic into presenters and helper functions and reduces some duplication in the views.
I had some timezone issues in my local environment so we'll need to see if the epoch check works properly on dev.

Member activity formatting improvements

---

app/Models/Helpers.php
app/Presenters/MemberPresenter.php

Revert some of the previous activity status changes since times provided through forum sync are stored in local time, not UTC.

Fix activity status again

---

app/Http/Controllers/DivisionStructureController.php
app/Nova/Division.php

- Expands the exception handling to include all exceptions, which fixes `500` errors from taking over when no structure is defined, which happens when new divisions are created
- Reports compilation errors as toast messages instead of outputing to the editor textarea
- Adds division structure edit field to the Nova Division model
Fixes #335

Hotfix for division structure undefined bug

---

app/Http/Controllers/Controller.php
app/Http/Controllers/DivisionController.php

Disable Discord notification when editing division settings if no actual changes were made. (closes #298)

Only show notification if division settings actually change

---

resources/views/division/inactive-members.blade.php
resources/views/division/partials/flagged-members.blade.php

Fixes #327
Also drops the bb-code section since that didn't appear to get much use. Folks wanting to share the information can just link to that particular page on the tracker

Handle discord in flagged inactives

---

app/Filament/Resources/DivisionResource.php
app/Models/Division.php
database/migrations/2019_12_14_000001_add_expiration_to_personal_access_tokens_table.php
database/migrations/2024_07_22_155600_add_logo_column_to_divisions_table.php
public/storage
resources/views/leave/edit.blade.php
resources/views/leave/forms/create-leave.blade.php
resources/views/leave/forms/delete-leave.blade.php
resources/views/leave/forms/edit-leave.blade.php

- Allows for upload of the division logo at the point of creation (or later)
- Cleans up overall fields
- Removes the need to keep division logos in version control for either the tracker or the site - these can be cleaned up later once we've migrated them over
- Fixes a few various forms missing CSRF and method field

Division logos

---

app/Filament/Resources/DivisionResource.php
app/Models/Activity.php
app/Models/Census.php
app/Models/Division.php
app/Models/Handle.php
app/Models/Rank.php
app/Models/Role.php
resources/views/leave/forms/create-leave.blade.php

- Drops fillable properties for guarded for models only modifiable from Filament
- Get rid of pointless slug setter (I blame lack of sleep)
- LOA create form `end_date` wasn't properly identified 
- Adds a filament filter for active division, and makes it the default

Various hotfixes, division resource filter

---

app/Models/Bot/Commands/Division.php
app/Models/Division.php
app/Models/Helpers.php
app/Notifications/DivisionEdited.php
app/Notifications/MemberNameChanged.php
app/Notifications/MemberRemoved.php
app/Notifications/MemberRequestApproved.php
app/Notifications/MemberRequestDenied.php
app/Notifications/MemberRequestHoldLifted.php
app/Notifications/MemberRequestPutOnHold.php
app/Notifications/MemberTransferred.php
app/Notifications/NewExternalRecruit.php
app/Notifications/NewMemberRecruited.php
app/Notifications/PartTimeMemberRemoved.php
app/Transformers/DivisionBasicTransformer.php
resources/views/application/components/division-heading.blade.php
resources/views/home/partials/divisions.blade.php
resources/views/leave/forms/edit-leave.blade.php
resources/views/member/forms/recruiter.blade.php
resources/views/member/partials/part-time-divisions.blade.php
resources/views/recruit/index.blade.php
resources/views/reports/leadership.blade.php

- Replaces the error-prone method of looking up division icons and instead uses the uploaded logo
- Hotfix for LOA creation

Logo path revamp

---

app/Channels/BotChannel.php
app/Channels/Messages/BotReactMessage.php
app/Filament/Resources/TicketResource.php
app/Http/Controllers/TicketController.php
app/Models/Ticket.php
database/migrations/2024_08_02_165416_rename_message_id_column_on_tickets_table.php

Ticket message id field is ambiguous so I've renamed it to make explicitly clear that it is external. Also replaced references to the field with a boolean since they are only checking that the field is set
Also updates the filament resource to make it read only

Improve message id naming

---

resources/views/help/partials/member-properties.blade.php

Update division structure documentation to use `.getLabel()` rather than `.name`.

Division structure documentation update

---

app/Http/Controllers/RecruitingController.php
app/Jobs/SyncDiscordMember.php
app/Models/Member.php
app/Services/AODClient.php

This PR does two things:
1. Add the AODClient services to communicate with the bot API.
2. Adds the SyncDiscordMember job triggered on a completed recruitment to trigger the Discord bot to sync their profile.

Add AODClient and Discord Member Sync

---

app/Enums/Position.php
app/Enums/Rank.php
app/Filament/Resources/DivisionResource.php
app/Filament/Resources/LeaveResource.php
app/Filament/Resources/MemberResource.php
app/Filament/Resources/TransferResource.php
app/Http/Controllers/API/v1/DivisionController.php
app/Models/Member.php
app/Presenters/MemberPresenter.php
app/Transformers/DivisionBasicTransformer.php
app/Transformers/MemberBasicTransformer.php
app/Transformers/MemberFullTransformer.php

Also removes some data from the basic member transform, and expands some values (rank, position) now that they are enums and won't result in nested queries

Add leaders data to divisions

---

app/Filament/Resources/HandleResource.php
app/Http/Controllers/RecruitingController.php
app/Http/Requests/DeleteMember.php
app/Notifications/MemberRemoved.php
app/Notifications/NewExternalRecruit.php
app/Notifications/NewMemberRecruited.php
app/Notifications/PartTimeMemberRemoved.php
database/factories/HandleFactory.php
resources/views/member/forms/remove-member-form.blade.php

This PR adds the member's in-game handle and platoon/squad to Discord recruitment and removal notifications. The additional information will help some divisions that may need further action after recruitment or removal, such as in-game clan/outfit management activities.
Recruitment Notification
Main Division Removal Notification
Part Time Divsion Removal Notification

Add additional info to recruitment and removal messages

---

app/Http/Controllers/MemberController.php
resources/views/member/search-ajax.blade.php
resources/views/member/search.blade.php

Add in-game handle as another criterion to match when searching via the search bar or search page. Matches based on in-game handle will display the matched handle as part of the search results. If multiple handles match for a single member, only the first match is displayed. 
Closes #193

Query in-game handles in addition to member name when searching

---

app/Filament/Mod/Resources/DivisionResource.php
app/Filament/Mod/Resources/MemberAwardResource.php
app/Filament/Mod/Resources/RankActionResource.php

- Filter member searches for awards and ranks to only those in an active division
- Prevent deletion of locality repeater fields

Hotfix member search

---

resources/views/division/part-time.blade.php

Add LOA status to part time page (#465)

---

app/Filament/Mod/Resources/RankActionResource.php

- Allows visibility of past rank actions via filter
- Hides the justification edit field after a promotion is accepted
- Improves how dates (requested at, approved at) are displayed

Release filter

---

app/Filament/Mod/Resources/PlatoonResource.php
app/Filament/Mod/Resources/PlatoonResource/Pages/EditPlatoon.php
app/Filament/Mod/Resources/PlatoonResource/RelationManagers/SquadsRelationManager.php
app/Filament/Mod/Resources/SquadResource.php
app/Filament/Mod/Resources/SquadResource/Pages/EditSquad.php

Avoid bulk delete of platoons. Also ensure division leaders assigned to their divisions can delete platoons. Add explicit verbiage about deletion.

Fix division leader perms, remove deleteAny (#507)

---

app/Models/Handle/HasCustomAttributes.php
resources/views/member/partials/handle-link.blade.php

Some handles support special characters such as `#` which results in a non-functional URL.

Urlencode handles when used in a URL

---

app/Filament/Actions/Members/CleanupUnassignedLeadersAction.php
app/Filament/Admin/Resources/HandleResource.php
app/Filament/Admin/Resources/MemberResource/Pages/ListMembers.php
app/Models/Member.php

Minor improvements to the handles resource to allow for more verbose comments. We'll add these to the ingame handles form to make it easier to understand where they should come from. It should also be more obvious when deeplinking is possible.
Also adds an admin cleanup action group, and an action for correcting members who have `Position::SQUAD_LEADER` or `Position::PLATOON_LEADER` but aren't actually assigned as leaders of a squad or platoon

Release cleanup
